CiscoDevNet/webex-contact-center-widget-starter

Examples/Layouts/Demo_Widgets_Added_Desktop Layout.json, Examples/Layouts/Header_Added_Desktop Layout.json, Examples/Layouts/README.md
Header widget layout and Demo widgets layout added
=> Header widget layout and Demo widgets layout added

.gitignore, Examples/Widgets/RSS/src/[sandbox]/sandbox.ts, Examples/Widgets/RSS/src/components/App.scss, Examples/Widgets/RSS/src/components/App.ts, Examples/Widgets/RSS/src/index.ts, Examples/Widgets/Timer/src/components/App.scss
Updates include:
- dynnamic width
- update frequency attribute accessible
- transparent bg color
- update gitignore for global yarn-error.log
- add ellipses style (DEPENDENCY UPDATE: https://github.com/momentum-design/momentum-ui/pull/752/files)
=> RSS Feed Edits

Examples/Widgets/CovidByLocation/src/components/App.ts, Examples/Widgets/CovidByLocation/src/components/Graph.scss, Examples/Widgets/CovidByLocation/src/components/Graph.ts, Examples/Widgets/CovidByLocation/src/index.ts
Addressing a bug that was filed in Issues for CovidByLocation Widget.
- fixed the error situation and I have a PR for momentumUI to address the delay in clearing the combobox
- added a loading spinner for when graph is loading data
- removed redundant api calls for better efficiency
Issue Link: https://github.com/CiscoDevNet/webex-contact-center-widget-starter/issues/19
=> CovidByLocation Clear Bug

Examples/Layouts/README.md
=> Disclaimer added

Examples/Layouts/README.md, Examples/Layouts/Salesforce_Desktop.json
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
=> Added salesforce agent desktop layout

Examples/Widgets/HospitalBedCapacity/package.json, Examples/Widgets/HospitalBedCapacity/src/[sandbox]/sandbox.ts, Examples/Widgets/HospitalBedCapacity/src/components/HospitalDetails.ts, Examples/Widgets/HospitalBedCapacity/src/components/HospitalItem.scss, Examples/Widgets/HospitalBedCapacity/src/components/HospitalItem.ts, Examples/Widgets/HospitalBedCapacity/src/components/HospitalWidget.scss, Examples/Widgets/HospitalBedCapacity/src/components/HospitalWidget.ts, Examples/Widgets/HospitalBedCapacity/src/components/Hospitals.scss, Examples/Widgets/HospitalBedCapacity/src/components/Hospitals.ts, Examples/Widgets/HospitalBedCapacity/src/index.ts
Hospital bed Expansion
I still have a few styling tweaks to make as well has handle more loading and error handling cases.
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
=> Hospital Bed Expansion

.github/CODEOWNERS
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
=> updated code owner

docs/index.md, index.md
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
=> added hosted demo widget js

demo.js, index.html, style.css
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
=> updated layout and examples

Examples/README.md, demo.js, style.css
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
=> added news widgets

Examples/Layouts/MSDynamics_CX-6589_workaround.json, Examples/Layouts/MSDynamics_Desktop.json, Examples/Layouts/README.md, Examples/Layouts/Salesforce_Desktop.json, Examples/Layouts/Salesforce_Desktop_CX-6589_workaround.json, Examples/Layouts/Zendesk_Desktop.json, Examples/Layouts/Zendesk_Desktop_CX-6589_workaround.json
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
=> Added Zendesk desktop layout json file. This will be used by our customers who uses the Zendesk crm connector application

react/src/direflow-component/App.tsx
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
=> CX-7112 : Some of the sdk api not working as expected from demo widgets

react/src/direflow-component/App.tsx
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
=> Added updateCadVariable example

react/src/direflow-component/App.tsx
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
=> Added mockOutdialAniList Example

lit-element/src/components/App.ts, react/src/direflow-component/App.tsx
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
=> CX-7413 : JS-SDK: add capability to update widget header label at runtime

Examples/Layouts/Zendesk/README.md
Created Readme file with the link to the new repo
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
=> Created Readme file with the link to the new repo

react/package.json, react/src/direflow-component/App.tsx
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
=> #CX-9905: Version updates and error fix

Iframe_Widget_Allowedparams.json
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
=> Added new layout json

react/package.json
> There doesn't appear to be any such doc
Bug fix. The React project does not build successfully, this change fixes multiple build errors.
Multiple build errors in the React project.
The React project compiles and runs.
No
=> Fix build failures in React project

CONTRIBUTING.md, README.md
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
=> Adding useful resources links in contributing document

react/package.json, react/src/direflow-component/App.tsx
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
=> #CX-11313 : Added monitoring & bargin  example

react/src/direflow-component/App.tsx
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
=> removeAllEventListeners for monitoring

react/direflow-webpack.js
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
=> #CX-12275 - Fixed fails to compile on react project

react/package.json, react/src/direflow-component/App.tsx
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
=> #CX-12488 : Updated example with new change

lit-element/package.json, lit-element/src/components/App.ts, react/package.json, react/src/direflow-component/App.tsx
Exposing new and existing logout functionality
`[Type here]`
`[Type here]`
`[Type here]`
=> Updating Major Version and expanding the logout functionality

docs/widgets/react-testing-gadget.js, widgets/react-testing-gadget.js
Update for internal testing
`[Type here]`
`[Type here]`
`[Type here]`
`[Type here]`
=> chore: update react-testing-gadget.js
